//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoApiFW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoDistance
    {
        public string Source { get; set; }
        public string Destination { get; set; }
        public decimal KMS { get; set; }
        public int Hits { get; set; }
    }
}
